site_name: yashk's iiitd notes

theme:
  name: material
  features:
    - navigation.tabs
  icon: 
    logo: material/memory
  favicon: assets/static/memory.png
  palette:

  # Light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: pink
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode

  # Dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: green
    accent: blue
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # - pymdownx.details
  # - pymdownx.magiclink
  # - pymdownx.tasklist:
  #     custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - admonition
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - roamlinks
  #- plantuml:
  #    puml_url: https://www.plantuml.com/plantuml/
  #    puml_keyword: plantuml
  - awesome-pages:
      sort_type: natural
